version: "3.1"

services:
  db_mysql:
    image: mysql:8.0
    container_name: mysql_c
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306

  react-app:
    build: front-end/
    stdin_open: true
    ports:
      - "3071:3000"
    environment:
      REACT_APP_API_KEY: ${REACT_APP_API_KEY}

  api-server:
    build: back-end/
    command: bash -c "npm run typeorm migration:run && npm run dev"
    ports:
      - "3072:3072"
    depends_on:
      - db_mysql
    environment:
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
